spring:
  application:
    name: Data HUB. API.

server.error:
  include-exception: true
  include-stacktrace: never
  whitelabel.enabled: false

---

springdoc:
  swagger-ui:
    tags-sorter: alpha

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    platform: postgres
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: org.postgresql.Driver

#server:
#  port: 8082

logging:
  config: classpath:log4j2-local.xml