name: Deploy to WSL2 Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build jar
        run: ./gradlew bootJar

      - name: Copy files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.WSL2_SSH_HOST }}
          username: ${{ secrets.WSL2_SSH_USER }}
          key: ${{ secrets.WSL2_SSH_PRIVATE_KEY }}
          source: |
            build/libs/*.jar
            Dockerfile
          target: /home/uk/app

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.WSL2_SSH_PRIVATE_KEY }}

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.WSL2_SSH_HOST }}
          port: ${{ secrets.WSL2_SSH_PORT }}
          username: ${{ secrets.WSL2_SSH_USER }}
          key: ${{ secrets.WSL2_SSH_PRIVATE_KEY }}
          script: |
            cd /home/uk/app
            docker build -t datahub-image:latest .
            docker stop datahub-container || true
            docker rm datahub-container || true
            docker run -d --name datahub-container -p 8088:8088 --env-file .env datahub-image:latest
          
